#paths to directories
DataDir: 'resources/SampleData/'
DatabaseDir: 'resources/Databases/'
ResultsDir: 'results/'
ResourcesDir: 'resources/'


#Name of folder for the Peptonizer run in the results folder
ExperimentName: 'CAMPI1_SIHUMIx_allbacteria'

FilterSpectra: False
AddHostandCrapToDB: False

#xtandem parameters
search_engine : "xtandem"
xtandem_default: "/home/tanja/Peptonizer2000/Peptonizer2000/resources/XTandem/xtandem_default.xml" # X!Tandem default configuration file
xtandem_fmme: 0.02 #Fragment mass tolerance (default=0.4)
xtandem_fmmeu: 'DA' #Fragment mass tolerance unit (default="DA")
xtandem_pmmep: 10 #Precursor mass tolerance plus (default=100)
xtandem_pmmem: 10 # Precursor mass tolerance minus (default=100)
xtandem_pmmeu: 'ppm' #Precursor mass tolerance unit (default="ppm")
xtandem_mods_fixed: '57@C' #Fixed modifications, comma separated (default="57@C")
xtandem_mods_variable: '15.99@M,' # Variable modifications, e.g. "16@M", comma separated (default=None)
xtandem_mods_variable_nterm: '' #Variable N-terminal modifications, e.g."+42.0@[", comma separated (default=None)
xtandem_add_params: {} #Additional parameters for X!Tandem as json dictionary{"param1" : "value", "param2" : "value", ...} which will be added to thextandem_input.xml

#ms2rescore parameters
RescorePipeline: '"tandem"' # any of ['infer', 'pin', 'tandem', 'maxquant', 'msgfplus', 'peptideshaker']
RescoreFeatures: '[["searchengine", "ms2pip", "rt"]]' #[["searchengine", "ms2pip", "rt"]],
RunPercolator: 'true' #boolean
FragModel: '"HCD"' #fragmentation model used for ms2pip http://compomics.github.io/projects/ms2pip_c#specialized-prediction-models
Mods: 
      [["Carbamidomethyl", 4,57.021464,'"C"', 'false', 'false'],
       ["Oxidated", 35, 15.9949146, '"M"','true','false'],
       ["Acetyl", 1, 42.010565,'null','true','false'],
       ["Gln->pyro-Glu",28,-17.026549, '"Q"', 'true', 'false'],
       ["Glu->pyro-Glu", 27, -18.010565, '"E"', 'true',  'false'],
       ["Ammonia-loss", 385, -17.026549, '"C"', 'true','false']] #needs to be a lists of lists with name, unimod accession, mass shift, amino acid, n term (bool), c term (bool)


#sample specific parameters
SpectraFileType: '.mgf' #'.mgf' or '.mzML'
SampleName: 'CAMPI_SIHUMIx'  #needs to be the name of your spectrum file and the folder where you have that file
ReferenceDBName: 'SIHUMI_DB1UNIPROT'

#UnipeptQueryParameters
TaxaNumber: 50
targetTaxa: 2   #comma separated taxa to be included in Unipept query 
FDR: 0.005


#PepGM parameters
TaxaInPlot: 15       #how many taxa should appear in the final results barplot
TaxaInProteinCount: 15 #how many taxa should appear in the protein counting barplot
Alpha: [0.1,0.4,0.6,0.8,0.9] #increments of parameter alpha to use for the grid earch
Beta: [0.01,0.05,0.1,0.2,0.4] #range of parameter beta to use for the grid search
prior: [0.5]

